---
- name: Update repository
  package: name=* state=latest update_cache=yes

- name: Install list of packages
  action: package name="{{ item }}" state=latest update_cache=yes
  with_items:
    - git
    - make
    - gcc

- name: Clean Wazuh directory if exists
  file:
    state: absent
    path: "/root/wazuh"

- git:
    repo: 'https://github.com/wazuh/wazuh.git'
    dest: '/root/wazuh'

- name: Configure unattended installation
  lineinfile:
    dest: /root/wazuh/etc/preloaded-vars.conf
    line: "{{ item }}"
  with_items:
    - 'USER_LANGUAGE="en"'
    - 'USER_NO_STOP="y"'
    - 'USER_INSTALL_TYPE="server"'
    - 'USER_DIR="/var/ossec"'
    - 'USER_ENABLE_EMAIL="n"'
    - 'USER_WHITE_LIST="127.0.0.1/24"'
    - 'USER_ENABLE_SYSCHECK="y"'
    - 'USER_ENABLE_ROOTCHECK="y"'
    - 'USER_ENABLE_OPENSCAP="y"'
    - 'USER_ENABLE_SYSLOG="y"'
    - 'USER_ENABLE_AUTHD="n"'
    - 'USER_AUTO_START="y"'
    - 'USER_UPDATE="n"'

- name: Compiling and installing Wazuh (please wait)
  shell: /root/wazuh/install.sh

- name: Adding firewall Manager rule
  firewalld:
    zone: public
    port: 1514/udp
    permanent: true
    state: enabled

- name: Adding firewall Authd rule
  firewalld:
    zone: public
    port: 1515/tcp
    permanent: true
    state: enabled
    
- name: Restarting firewall
  service:
    name: firewalld
    state: restarted

- name: Starting wazuh-manager service
  service:
    name: wazuh-manager
    state: started

- name: Generate SSL files for authd
  command: "openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout sslmanager.key -out sslmanager.cert"
  args:
    creates: sslmanager.cert
    chdir: /var/ossec/etc/

- name: Starting authd
  shell: /var/ossec/bin/ossec-authd
    
